name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  REPORTER_TYPE: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          fail_on_error: true
          reporter: ${{ env.REPORTER_TYPE }}

  bun-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun ci

