# https://github.com/dependabot/dependabot-core/issues/6528#issuecomment-2013695799
name: 'Dependabot: patch bun.lockb'
on:
  pull_request:
    paths:
      - 'package.json'
permissions:
  contents: write
jobs:
  update-bun-lockb:
    name: 'Update bun.lockb'
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          bun install
          git add bun.lockb
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git commit --amend --no-edit
          git push --force
